name: build github actions angular
on:
  push:
    branches:
      - feature/*
jobs:
  build-feature:
    runs-on: windows-lastest
    steps:
      - uses: actions/checkout@v3
      - name: pull and checkout from git repository
        run: |
            echo "pulling and checking out from git repository"
      - name: Setup Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: Install npm package
        run: npm install
      - name: Install Angular CLI globally
        run: npm install -g @angular/cli
      - name: Run Angular tests
        run: |
            ng test --watch=false
            echo "run test en la app"
      - name: Build Angular app
        run: |
          ng build
          echo "build angular app"
